### ISSUE TITLE
[調査]トランザクションについて調べる。どのような目的で使い、どんな記述をするかまとめる。

### ISSUE THREAD

**Issue by ms2sato** [shuma1020/training_app#64]
調べる系。

トランザクションという概念がDB関連の用語で出てきます。これがどのようなものなのかを調べてこのIssueでまとめましょう。

**Comment by shuma1020** [comment]
@ms2sato 
自分のターミナルを確認したところ、transactionが出てくるのは複数のテーブルのデータを更新したりするとき
```
 User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Product Load (0.3ms)  SELECT "products".* FROM "products" WHERE "products"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/products_controller.rb:78:in `set_product'
   (0.1ms)  begin transaction
```
> SQL のトランザクションとは、簡単に言ってしまえば、複数の SQL 文によるデータ更新を1つの処理としてまとめてデータベースに反映させることです。

https://oss-db.jp/dojo/dojo_01
https://qiita.com/komattio/items/838ea5df68eb076e8099

**Comment by ms2sato** [comment]
@shuma1020 では、Railsでトランザクションを明示的に利用する際のことを調べましょう。

- どういう時に利用するのか
- どんな書き方をするのか

**Comment by shuma1020** [comment]
@ms2sato 
トランザクションはコントローラーにかけるのかと考えているのですが、
下記のようにかくとどのtransactionでも利用できるようになるとのことですが、これはどこに書けばいいのかいまいちわかりません。
```
ActiveRecord::Base.transaction do
  @item.アクセス処理
  @user.アクセス処理
end
```

**Comment by ms2sato** [comment]
@shuma1020 

## 理想的な方法
モデルにメソッドを作成し、その中でトランザクションを行う。
やれそうならチャレンジしてみてください。書籍などで紹介されているのを真似していたことがあるので、チャレンジする意味もありそうです。長くかかりそうなら撤退すべし。

## 今とりあえず許しても良い（ただし実際のサービスではレビューで指摘されるはず）方法
コントローラーのアクションの中で書く。あとで直してもらいますが。
「どこか」という話であれば、それは自身が一緒に処理したDBのまとまりを理解していれば書けますよね。DB処理をアトミックにするための処理です。

**Comment by shuma1020** [comment]
@ms2sato 
## 試したこと
結果：transactionと出ないのでうまくいっていない
```
def create
    Product.transaction do
      @product = Product.find(params[:product_id])
      @patron =@product.patrons.new(patron_params)
      @patron.user_id = current_user.id
      respond_to do |format|
        if @patron.save
          format.html { redirect_to @product, notice: 'パトロンになりました' }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new }
          format.json { render json: @product.errors, notice: '金額を入れてください' }
        end
      end
    end
  end
```
```
def create
    ActiveRecord::Base.transaction do
      @product = Product.find(params[:product_id])
      @patron =@product.patrons.new(patron_params)
      @patron.user_id = current_user.id
      respond_to do |format|
        if @patron.save
          format.html { redirect_to @product, notice: 'パトロンになりました' }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new }
          format.json { render json: @product.errors, notice: '金額を入れてください' }
        end
      end
    end
  end
```

**Comment by ms2sato** [comment]
@shuma1020 

### 確認すべきこと（前提）

ログで下記のように`BEGIN` - `COMMIT` と出る間がトランザクションです。その間に入っているDB変更がアトミックに扱われます。

```
  (0.2ms)  BEGIN
  ↳ app/controllers/mypage/products_controller.rb:26:in `block in create'
  Product Create (10.5ms)  INSERT INTO "products" ("title", "price", "description", "created_at", "updated_at", "message", "user_id", "image") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"  [["title", "テスト"], ["price", 1000], ["description", "テスト"], ["created_at", "2019-12-29 02:15:14.156783"], ["updated_at", "2019-12-29 02:15:14.156783"], ["message", "ああああ"], ["user_id", 2], ["image", "christopher-burns-gyrrWzwqm5Y-unsplash.jpg"]]
  ↳ app/controllers/mypage/products_controller.rb:26:in `block in create'
   (5.8ms)  COMMIT
```

### 書いてくれたコードへコメント

両者ともDBへの更新は@patronの保存一つなので、そもそもトランザクションする意味は無いです。
しても良いですが、する前と動きは変わらないはずです。

複数のDBへの更新（新規レコード作成、レコードの更新、削除）が対象であることを理解できると適切なコードにトランザクションできるでしょう。精査しきれていないですが、クラウドファンディングにはまだトランザクション対象が無いかもしれません。my_dictionary にはあると思います。

**Comment by shuma1020** [comment]
@ms2sato あっやはりそうでしたか。クラウドファンディングにそれっぽいところが見当たらなかったので、あるとすればcreateのあたりかと思いコーディングしていました。

**Comment by ms2sato** [comment]
@shuma1020 意味が理解できている様子なので、大丈夫かと。今後必要な時に指摘されずに自然に書けると良いです。
